<a href="https://colab.research.google.com/github/bayisabesalomo-hue/simple_web/blob/main/Assignment2_Load%2C_clean%2C_transform%2C_and_combine_three_Mexico_real_estate_datasets_into_a_single_DataFrame_ready_for_analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Assignment: Load, clean, transform, and combine three Mexico real-estate
datasets into a single DataFrame ready for analysis.***

In [ ]:
import pandas as pd

#Step 1: Read the three CSV files

In [ ]:
df1 = pd.read_csv("/content/mexico-real-estate-1.csv")

In [ ]:
df2 = pd.read_csv("/content/mexico-real-estate-2.csv")

In [ ]:
df3 = pd.read_csv("/content/mexico-real-estate-3.csv")

#Step 2: Inspect df1

In [ ]:
df1.shape

(700, 6)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    object
 1   state          700 non-null    object
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    object
dtypes: float64(3), object(3)
memory usage: 32.9+ KB

In [ ]:
df1.head()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

#Step 3: Clean df1

# Drop rows with any NaN value

In [ ]:
df1.dropna(inplace=True)

In [ ]:
df1.shape

(583, 6)

# Remove "$" and "," from price_usd, then cast to float

In [ ]:
df1["price_usd"] = (df1["price_usd"]
                  .str.replace("$", "", regex=False)
                  .str.replace(",", "", regex=False)
                  .astype(float)
)

In [ ]:
df1["price_usd"].head()

0     67965.56
1     63223.78
2     84298.37
3     94308.80
5    105191.37
Name: price_usd, dtype: float64

#  Step 4: Clean df2

# Drop rows with any NaN value

In [ ]:
df2.dropna(inplace=True)

# Convert MXN → USD (exchange rate: 19 pesos per dollar in 2014)

In [ ]:
df2["price_usd"] = df2["price_mxn"]/19

In [ ]:
df2["price_usd"].head()

0     68421.052632
2    278947.368421
6     65789.473684
7    111578.947368
8     39904.736842
Name: price_usd, dtype: float64

In [ ]:
df2.head()

,property_type,state,lat,lon,area_m2,price_mxn,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,1300000.0,68421.052632
2,house,Morelos,23.634501,-102.552788,360.0,5300000.0,278947.368421
6,apartment,Estado de México,19.272040,-99.572013,85.0,1250000.0,65789.473684
7,house,San Luis Potosí,22.138882,-100.996510,158.0,2120000.0,111578.947368
8,apartment,Distrito Federal,19.394558,-99.129707,65.0,758190.0,39904.736842

# Drop the original MXN column

In [ ]:
df2.drop(columns=["price_mxn"], inplace=True)

In [ ]:
df2.head()

,property_type,state,lat,lon,area_m2,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,68421.052632
2,house,Morelos,23.634501,-102.552788,360.0,278947.368421
6,apartment,Estado de México,19.272040,-99.572013,85.0,65789.473684
7,house,San Luis Potosí,22.138882,-100.996510,158.0,111578.947368
8,apartment,Distrito Federal,19.394558,-99.129707,65.0,39904.736842

#  Step 5: Clean df3 – split "lat-lon" into two columns

# Drop rows with any NaN value

In [ ]:
df3.dropna(inplace=True)

In [ ]:
df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67
5,house,|México|Jalisco|Guadalajara|,"20.689157,-103.366728",175.0,102763.00

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 582 entries, 0 to 699
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            582 non-null    object
 1   place_with_parent_names  582 non-null    object
 2   lat-lon                  582 non-null    object
 3   area_m2                  582 non-null    float64
 4   price_usd                582 non-null    float64
dtypes: float64(2), object(3)
memory usage: 27.3+ KB

# Split the "lat-lon" string on the comma separator

In [ ]:
df3[["lat","lon"]] = df3 ["lat-lon"].str.split(",", expand=True)

In [ ]:
df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd,lat,lon
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59,19.52589,-99.151703
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73,19.2640539,-99.5727534
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69,19.268629,-99.671722
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67,19.511938,-96.871956
5,house,|México|Jalisco|Guadalajara|,"20.689157,-103.366728",175.0,102763.00,20.689157,-103.366728

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 582 entries, 0 to 699
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            582 non-null    object
 1   place_with_parent_names  582 non-null    object
 2   lat-lon                  582 non-null    object
 3   area_m2                  582 non-null    float64
 4   price_usd                582 non-null    float64
 5   lat                      582 non-null    object
 6   lon                      582 non-null    object
dtypes: float64(2), object(5)
memory usage: 36.4+ KB

In [ ]:
df3["lon"] = df3["lon"].astype(float)
df3["lat"] = df3["lat"].astype(float)

#Step 6: Extract state name, drop unneeded columns

# State name is the 3rd segment (index 2) after splitting on "|"

# Format example: "México|Jalisco|Guadalajara|..."

In [ ]:
df3["state"] = df3["place_with_parent_names"].str.split("|").str[2]

In [ ]:
df3.head()

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd,lat,lon,state
0,apartment,|México|Distrito Federal|Gustavo A. Madero|Acu...,"19.52589,-99.151703",71.0,48550.59,19.525890,-99.151703,Distrito Federal
1,house,|México|Estado de México|Toluca|Metepec|,"19.2640539,-99.5727534",233.0,168636.73,19.264054,-99.572753,Estado de México
2,house,|México|Estado de México|Toluca|Toluca de Lerd...,"19.268629,-99.671722",300.0,86932.69,19.268629,-99.671722,Estado de México
4,apartment,|México|Veracruz de Ignacio de la Llave|Veracruz|,"19.511938,-96.871956",84.0,68508.67,19.511938,-96.871956,Veracruz de Ignacio de la Llave
5,house,|México|Jalisco|Guadalajara|,"20.689157,-103.366728",175.0,102763.00,20.689157,-103.366728,Jalisco

# Remove the original columns that are no longer needed

In [ ]:
df3.drop(columns=["place_with_parent_names", "lat-lon"], inplace=True)

#Step 7: Concatenate all three DataFrames

In [ ]:
df = pd.concat([df1,df2,df3], ignore_index=True)

In [ ]:
df.head()

  property_type             state        lat         lon  area_m2  price_usd
0         house  Estado de México  19.560181  -99.233528    150.0   67965.56
1         house        Nuevo León  25.688436 -100.198807    186.0   63223.78
2     apartment          Guerrero  16.767704  -99.764383     82.0   84298.37
3     apartment          Guerrero  16.829782  -99.911012    150.0   94308.80
4         house           Yucatán  21.052583  -89.538639    205.0  105191.37

In [ ]:
df.shape

(1736, 6)